<?php

/**
 * Implementation of hook_menu().
 */
function camp_schedule_menu() {
  $items = array();
  $items['admin/settings/camp-schedule'] = array(
    'title' => 'Camp Schedule Settings',
    'description' => 'Settings related to the camp schedule module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camp_schedule_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('manage schedule'),
    'file' => 'camp_schedule.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['admin/content/camp-schedule'] = array(
    'title' => 'Camp Schedule',
    'description' => 'Arrange nodes into the camp schedule.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('camp_schedule_manage_form'),
    'access callback' => 'user_access',
    'access arguments' => array('manage schedule'),
    'file' => 'camp_schedule.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function camp_schedule_perm() {
  return array('manage schedule');
}

/**
 * Implementation of hook_theme().
 */
function camp_schedule_theme() {
  return array(
    'camp_schedule_manage_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'camp_schedule.admin.inc',
    )
  );
}

/**
 * Implementation of hook_help().
 */
function camp_schedule_help($path) {
  switch ($path) {
    case 'admin/settings/camp-schedule':
      return '<p>'. t('Use the form below to select the node types you\'d like to select from when making your schedule.') .'</p>';
  }
}

/**
 * Implementation of hook_views_api().
 */
function camp_schedule_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'camp_schedule'),
  );
}
